// === PAGE RENDERERS ===
const PAGES={};const INIT={};

// ========== DASHBOARD ==========
PAGES.dashboard=()=>`<div class="page-header"><h1>Selamat Datang! 👋</h1><p>Ringkasan data sistem pendaftaran siswa.</p></div>
<div class="stats-grid"><div class="stat-card students"><div class="stat-icon"><i class="bi bi-people-fill"></i></div><div class="stat-value" id="s1">0</div><div class="stat-label">Total Siswa</div></div><div class="stat-card classes"><div class="stat-icon"><i class="bi bi-book-fill"></i></div><div class="stat-value" id="s2">0</div><div class="stat-label">Total Kelas</div></div><div class="stat-card registrations"><div class="stat-icon"><i class="bi bi-clipboard2-check-fill"></i></div><div class="stat-value" id="s3">0</div><div class="stat-label">Registrasi</div></div><div class="stat-card capacity"><div class="stat-icon"><i class="bi bi-wallet2"></i></div><div class="stat-value" id="s4">0</div><div class="stat-label">Pemasukan</div></div></div>
<div class="grid-3"><div class="panel"><div class="panel-header"><div class="panel-title"><i class="bi bi-graph-up"></i> Tren Registrasi</div></div><div class="panel-body"><div class="chart-container"><canvas id="chTrend"></canvas></div></div></div><div class="panel"><div class="panel-header"><div class="panel-title"><i class="bi bi-clock-history"></i> Aktivitas</div></div><div class="panel-body"><ul class="activity-list" id="actList"></ul></div></div></div>
<div class="grid-2"><div class="panel"><div class="panel-header"><div class="panel-title"><i class="bi bi-bar-chart-fill"></i> Per Kategori</div></div><div class="panel-body"><div class="chart-container"><canvas id="chCat"></canvas></div></div></div><div class="panel"><div class="panel-header"><div class="panel-title"><i class="bi bi-pie-chart-fill"></i> Gender</div></div><div class="panel-body"><div class="chart-container" style="max-width:300px;margin:0 auto"><canvas id="chGender"></canvas></div></div></div></div>`;
INIT.dashboard=()=>{animNum('s1',D.students.length);animNum('s2',D.classes.length);animNum('s3',D.registrations.length);const inc=D.payments.filter(p=>p.status==='paid').reduce((s,p)=>s+Number(p.amount||0),0);document.getElementById('s4').textContent=fmtMoney(inc);
// Charts
Object.values(charts).forEach(c=>{try{c.destroy()}catch(e){}});
const catMap={};D.registrations.forEach(r=>{catMap[r.class_category]=(catMap[r.class_category]||0)+1});
const colors=['#4f46e5','#10b981','#f59e0b','#ef4444','#06b6d4','#8b5cf6','#ec4899'];
charts.cat=new Chart(document.getElementById('chCat'),{type:'bar',data:{labels:Object.keys(catMap).length?Object.keys(catMap):['—'],datasets:[{data:Object.values(catMap).length?Object.values(catMap):[0],backgroundColor:colors,borderRadius:8,borderSkipped:false}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{y:{beginAtZero:true,ticks:{stepSize:1}},x:{grid:{display:false}}}}});
const gMap={};D.students.forEach(s=>{gMap[s.gender]=(gMap[s.gender]||0)+1});
charts.gender=new Chart(document.getElementById('chGender'),{type:'doughnut',data:{labels:Object.keys(gMap).length?Object.keys(gMap):['—'],datasets:[{data:Object.values(gMap).length?Object.values(gMap):[1],backgroundColor:Object.keys(gMap).length?['#4f46e5','#f59e0b']:['#e2e8f0'],borderWidth:0}]},options:{responsive:true,maintainAspectRatio:false,cutout:'65%',plugins:{legend:{position:'bottom'}}}});
// Trend chart
const months={};for(let i=5;i>=0;i--){const d=new Date();d.setMonth(d.getMonth()-i);const k=d.toISOString().slice(0,7);months[k]=0}
D.registrations.forEach(r=>{if(r.registration_date){const k=r.registration_date.slice(0,7);if(months[k]!==undefined)months[k]++}});
charts.trend=new Chart(document.getElementById('chTrend'),{type:'line',data:{labels:Object.keys(months).map(m=>{const[y,mo]=m.split('-');return['Jan','Feb','Mar','Apr','Mei','Jun','Jul','Agu','Sep','Okt','Nov','Des'][parseInt(mo)-1]+' '+y.slice(2)}),datasets:[{data:Object.values(months),borderColor:'#4f46e5',backgroundColor:'rgba(79,70,229,.1)',fill:true,tension:.4,borderWidth:2,pointRadius:4,pointBackgroundColor:'#4f46e5'}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{y:{beginAtZero:true,ticks:{stepSize:1}},x:{grid:{display:false}}}}});
// Activity
const al=document.getElementById('actList');const items=[];
D.students.slice(0,3).forEach(s=>items.push({i:'bi-person-plus',bg:'var(--primary-subtle)',c:'var(--primary)',t:`<strong>${E(s.name)}</strong> mendaftar`,d:fmtDate(s.created_at)}));
D.registrations.slice(0,3).forEach(r=>items.push({i:'bi-check-circle',bg:'var(--success-subtle)',c:'var(--success)',t:`<strong>${E(r.student_name)}</strong> → ${E(r.class_name)}`,d:fmtDate(r.registration_date)}));
al.innerHTML=items.length?items.slice(0,6).map(x=>`<li class="activity-item"><div class="activity-icon" style="background:${x.bg};color:${x.c}"><i class="bi ${x.i}"></i></div><div><div class="activity-text">${x.t}</div><div class="activity-time">${x.d}</div></div></li>`).join(''):'<div class="empty-state"><p>Belum ada aktivitas</p></div>'};

// ========== STUDENTS ==========
PAGES.students=()=>`<div class="page-header"><h1>Data Siswa</h1><p>Kelola data siswa terdaftar.</p></div>
<div class="panel"><div class="panel-header"><div class="search-box"><i class="bi bi-search"></i><input placeholder="Cari siswa..." oninput="filterTbl('students',this.value)"></div><div class="panel-actions"><button class="btn btn-outline btn-sm" onclick="exportCSV('students')"><i class="bi bi-download"></i> Export</button><button class="btn btn-primary btn-sm" onclick="modalStudent()"><i class="bi bi-plus-lg"></i> Tambah</button></div></div><div class="table-wrapper"><table class="data-table"><thead><tr><th>Siswa</th><th>Telepon</th><th>Gender</th><th>Usia</th><th>Pendidikan</th><th>Status</th><th>Terdaftar</th><th>Aksi</th></tr></thead><tbody id="tblStudents"></tbody></table></div></div>`;
INIT.students=()=>{renderStudents(D.students)};
function renderStudents(list){document.getElementById('tblStudents').innerHTML=list.length?list.map(s=>`<tr><td><div class="user-cell"><img class="avatar-sm" src="https://ui-avatars.com/api/?name=${enc(s.name)}&background=eef2ff&color=4f46e5&size=32"><div><div class="name">${E(s.name)}</div><div class="email">${E(s.email)}</div></div></div></td><td>${E(s.phone)}</td><td><span class="badge ${s.gender==='Laki-laki'?'badge-info':'badge-warning'}">${E(s.gender)}</span></td><td>${s.age}</td><td>${s.education_level?`<span class="badge badge-primary">${E(s.education_level)}</span>`:'-'}</td><td><span class="badge ${(s.status||'active')==='active'?'badge-success':'badge-danger'}">${(s.status||'active')==='active'?'Aktif':'Nonaktif'}</span></td><td>${fmtDate(s.created_at)}</td><td><div class="action-btns"><button class="btn btn-ghost btn-icon" onclick="modalStudent(${s.id})"><i class="bi bi-pencil"></i></button><button class="btn btn-ghost btn-icon" style="color:var(--danger)" onclick="delStudent(${s.id})"><i class="bi bi-trash3"></i></button></div></td></tr>`).join(''):'<tr><td colspan="8"><div class="empty-state"><i class="bi bi-people"></i><p>Belum ada data</p></div></td></tr>'}
function modalStudent(id){const s=id?D.students.find(x=>x.id==id):null;openModal(`<div class="modal-header"><h3>${s?'Edit':'Tambah'} Siswa</h3><button class="modal-close" onclick="closeModal()"><i class="bi bi-x-lg"></i></button></div><div class="modal-body"><form onsubmit="saveStudent(event,${id||0})"><input type="hidden" id="fSid" value="${id||''}"><div class="form-row"><div class="form-group"><label class="form-label">Nama *</label><input class="form-control" id="fSname" value="${E(s?.name||'')}" required></div><div class="form-group"><label class="form-label">Email *</label><input class="form-control" type="email" id="fSemail" value="${E(s?.email||'')}" required></div></div><div class="form-row"><div class="form-group"><label class="form-label">Telepon *</label><input class="form-control" id="fSphone" value="${E(s?.phone||'')}" required></div><div class="form-group"><label class="form-label">Usia *</label><input class="form-control" type="number" id="fSage" value="${s?.age||''}" required></div></div><div class="form-row"><div class="form-group"><label class="form-label">Gender *</label><select class="form-control" id="fSgender" required><option value="">Pilih</option><option ${s?.gender==='Laki-laki'?'selected':''}>Laki-laki</option><option ${s?.gender==='Perempuan'?'selected':''}>Perempuan</option></select></div><div class="form-group"><label class="form-label">Pendidikan</label><select class="form-control" id="fSedu"><option value="">Pilih</option><option ${s?.education_level==='SD'?'selected':''}>SD</option><option ${s?.education_level==='SMP'?'selected':''}>SMP</option><option ${s?.education_level==='SMA'?'selected':''}>SMA</option></select></div></div><div class="form-group"><label class="form-label">Alamat *</label><textarea class="form-control" id="fSaddr" required>${E(s?.address||'')}</textarea></div><div class="modal-footer"><button type="button" class="btn btn-outline" onclick="closeModal()">Batal</button><button type="submit" class="btn btn-primary"><i class="bi bi-check-lg"></i> Simpan</button></div></form></div>`)}
async function saveStudent(e,id){e.preventDefault();const b={name:g('fSname'),email:g('fSemail'),phone:g('fSphone'),age:g('fSage'),gender:g('fSgender'),education_level:g('fSedu'),address:g('fSaddr')};if(id)b.id=id;try{const r=await fetch(API+'/students.php',{method:id?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)});const d=await r.json();if(d.success||d.id){toast(id?'Siswa diperbarui':'Siswa ditambahkan');closeModal();await loadAllData();renderStudents(D.students)}else toast(d.message||'Gagal','error')}catch(e){toast('Server error','error')}}
function delStudent(id){const s=D.students.find(x=>x.id==id);showConfirm(`Hapus "${s?.name}"?`,async()=>{try{await fetch(API+'/students.php',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id})});toast('Dihapus');await loadAllData();renderStudents(D.students)}catch(e){toast('Error','error')}})}
function g(id){return document.getElementById(id)?.value||''}

// ========== CLASSES ==========
PAGES.classes=()=>`<div class="page-header"><h1>Kelas & Program</h1><p>Kelola kelas, jadwal, dan instruktur.</p></div>
<div class="panel"><div class="panel-header"><div class="search-box"><i class="bi bi-search"></i><input placeholder="Cari kelas..." oninput="filterTbl('classes',this.value)"></div><div class="panel-actions"><button class="btn btn-primary btn-sm" onclick="modalClass()"><i class="bi bi-plus-lg"></i> Tambah</button></div></div><div class="table-wrapper"><table class="data-table"><thead><tr><th>Nama Kelas</th><th>Kategori</th><th>Jadwal</th><th>Instruktur</th><th>Kapasitas</th><th>Harga</th><th>Aksi</th></tr></thead><tbody id="tblClasses"></tbody></table></div></div>`;
INIT.classes=()=>{renderClasses(D.classes)};
function renderClasses(list){document.getElementById('tblClasses').innerHTML=list.length?list.map(c=>{const reg=D.registrations.filter(r=>r.class_id==c.id).length;const pct=c.capacity>0?Math.round(reg/c.capacity*100):0;return`<tr><td><strong>${E(c.name)}</strong></td><td><span class="badge badge-primary">${E(c.category)}</span></td><td><i class="bi bi-clock" style="color:var(--text-light)"></i> ${E(c.schedule)}</td><td>${E(c.instructor||'-')}</td><td><span class="badge ${pct>=90?'badge-danger':pct>=50?'badge-warning':'badge-success'}">${reg}/${c.capacity}</span></td><td>${fmtMoney(c.price)}</td><td><div class="action-btns"><button class="btn btn-ghost btn-icon" onclick="modalClass(${c.id})"><i class="bi bi-pencil"></i></button><button class="btn btn-ghost btn-icon" style="color:var(--danger)" onclick="delClass(${c.id})"><i class="bi bi-trash3"></i></button></div></td></tr>`}).join(''):'<tr><td colspan="7"><div class="empty-state"><p>Belum ada kelas</p></div></td></tr>'}
function modalClass(id){const c=id?D.classes.find(x=>x.id==id):null;openModal(`<div class="modal-header"><h3>${c?'Edit':'Tambah'} Kelas</h3><button class="modal-close" onclick="closeModal()"><i class="bi bi-x-lg"></i></button></div><div class="modal-body"><form onsubmit="saveClass(event,${id||0})"><div class="form-group"><label class="form-label">Nama *</label><input class="form-control" id="fCname" value="${E(c?.name||'')}" required></div><div class="form-row"><div class="form-group"><label class="form-label">Kategori *</label><select class="form-control" id="fCcat" required><option value="">Pilih</option>${['Calistung','SD — Matematika','SD — Bahasa Inggris','SMP — Matematika','SMP — Bahasa Inggris','Melukis'].map(x=>`<option ${c?.category===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="form-group"><label class="form-label">Jadwal *</label><input class="form-control" id="fCsched" value="${E(c?.schedule||'')}" required></div></div><div class="form-row"><div class="form-group"><label class="form-label">Kapasitas *</label><input class="form-control" type="number" id="fCcap" value="${c?.capacity||20}" required></div><div class="form-group"><label class="form-label">Harga *</label><input class="form-control" type="number" id="fCprice" value="${c?.price||''}" required></div></div><div class="form-group"><label class="form-label">Instruktur</label><input class="form-control" id="fCinst" value="${E(c?.instructor||'')}"></div><div class="modal-footer"><button type="button" class="btn btn-outline" onclick="closeModal()">Batal</button><button type="submit" class="btn btn-primary"><i class="bi bi-check-lg"></i> Simpan</button></div></form></div>`)}
async function saveClass(e,id){e.preventDefault();const b={name:g('fCname'),category:g('fCcat'),schedule:g('fCsched'),capacity:g('fCcap'),price:g('fCprice')};if(id)b.id=id;try{const r=await fetch(API+'/classes.php',{method:id?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)});const d=await r.json();if(d.success||d.id){toast(id?'Diperbarui':'Ditambahkan');closeModal();await loadAllData();renderClasses(D.classes)}else toast(d.message||'Gagal','error')}catch(e){toast('Error','error')}}
function delClass(id){showConfirm('Hapus kelas ini?',async()=>{try{await fetch(API+'/classes.php',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id})});toast('Dihapus');await loadAllData();renderClasses(D.classes)}catch(e){toast('Error','error')}})}

// ========== REGISTRATIONS ==========
PAGES.registrations=()=>`<div class="page-header"><h1>Registrasi</h1><p>Data pendaftaran siswa ke kelas.</p></div>
<div class="panel"><div class="panel-header"><div class="search-box"><i class="bi bi-search"></i><input placeholder="Cari..." oninput="filterTbl('registrations',this.value)"></div><div class="panel-actions"><button class="btn btn-outline btn-sm" onclick="exportCSV('registrations')"><i class="bi bi-download"></i> Export</button></div></div><div class="table-wrapper"><table class="data-table"><thead><tr><th>#</th><th>Siswa</th><th>Kelas</th><th>Kategori</th><th>Tanggal</th><th>Aksi</th></tr></thead><tbody id="tblRegs"></tbody></table></div></div>`;
INIT.registrations=()=>{renderRegs(D.registrations)};
function renderRegs(list){document.getElementById('tblRegs').innerHTML=list.length?list.map((r,i)=>`<tr><td>${i+1}</td><td><strong>${E(r.student_name)}</strong></td><td>${E(r.class_name)}</td><td><span class="badge badge-primary">${E(r.class_category)}</span></td><td>${fmtDate(r.registration_date)}</td><td><button class="btn btn-ghost btn-icon" style="color:var(--danger)" onclick="delReg(${r.id})"><i class="bi bi-trash3"></i></button></td></tr>`).join(''):'<tr><td colspan="6"><div class="empty-state"><p>Belum ada registrasi</p></div></td></tr>'}
function delReg(id){showConfirm('Hapus registrasi?',async()=>{try{await fetch(API+'/registrations.php?id='+id,{method:'DELETE'});toast('Dihapus');await loadAllData();renderRegs(D.registrations)}catch(e){toast('Error','error')}})}

// ========== FILTER & EXPORT ==========
function filterTbl(type,q){q=q.toLowerCase();if(type==='students')renderStudents(D.students.filter(s=>s.name.toLowerCase().includes(q)||s.email.toLowerCase().includes(q)));else if(type==='classes')renderClasses(D.classes.filter(c=>c.name.toLowerCase().includes(q)||c.category.toLowerCase().includes(q)));else if(type==='registrations')renderRegs(D.registrations.filter(r=>r.student_name.toLowerCase().includes(q)||r.class_name.toLowerCase().includes(q)));else if(type==='payments')renderPayments(D.payments.filter(p=>(p.student_name||'').toLowerCase().includes(q)));else if(type==='contacts')renderContacts(D.contacts.filter(c=>c.name.toLowerCase().includes(q)||c.subject?.toLowerCase().includes(q)))}
function exportCSV(type){let rows=[],headers=[];if(type==='students'){headers=['Nama','Email','Telepon','Gender','Usia','Pendidikan','Status','Terdaftar'];rows=D.students.map(s=>[s.name,s.email,s.phone,s.gender,s.age,s.education_level||'',s.status||'active',s.created_at])}else if(type==='registrations'){headers=['Siswa','Kelas','Kategori','Tanggal'];rows=D.registrations.map(r=>[r.student_name,r.class_name,r.class_category,r.registration_date])}else if(type==='payments'){headers=['Siswa','Kelas','Jumlah','Metode','Status','Periode','Tanggal'];rows=D.payments.map(p=>[p.student_name||'',p.class_name||'',p.amount,p.payment_method,p.status,p.period||'',p.payment_date])}let csv=headers.join(',')+'\n'+rows.map(r=>r.map(c=>'"'+(c||'')+'"').join(',')).join('\n');const blob=new Blob([csv],{type:'text/csv'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=type+'_export.csv';a.click();toast('File exported')}
